const actions = {
  CART_COMPUTE_SUBTOTAL: 'CART_COMPUTE_SUBTOTAL',
  CART_COMPUTE_SHIPPING: 'CART_COMPUTE_SHOPPING',
  CART_COMPUTE_DISCOUNT: 'CART_COMPUTE_DISCOUNT',
  CART_COMPUTE_TOTAL: 'CART_COMPUTE_TOTAL',
  CART_UPDATE_PRODUCTS: 'CART_UPDATE_PRODUCTS',
}

export default actions
